-- Generated by tools/generate_resource_converter_catalog.py
-- Source: bn/game0/data/json/items
-- Metadata only. Category index is stored in generated_catalog_category_items.lua and item records in generated_catalog_items.lua
-- Do not edit this file by hand. Regenerate it with the script.

return {
  categories = {
    {
      count = 409,
      desc = locale.gettext("枪械、弓弩与其他远程武器。"),
      id = "weapons_ranged",
      name = locale.gettext("枪械与远程"),
    },
    {
      count = 334,
      desc = locale.gettext("子弹、电池、燃料弹药与可堆叠弹药。"),
      id = "ammo",
      name = locale.gettext("弹药"),
    },
    {
      count = 212,
      desc = locale.gettext("弹匣、供弹机构与相关附件。"),
      id = "magazines",
      name = locale.gettext("弹匣与供弹"),
    },
    {
      count = 1197,
      desc = locale.gettext("护具、服装、携行穿戴与宠物护甲。"),
      id = "armor",
      name = locale.gettext("护甲与穿戴"),
    },
    {
      count = 354,
      desc = locale.gettext("常规工具、电子设备与可激活装置。"),
      id = "tools",
      name = locale.gettext("工具与电子"),
    },
    {
      count = 935,
      desc = locale.gettext("食物、饮料、药品和一般消耗品。"),
      id = "consumables",
      name = locale.gettext("食物与药品"),
    },
    {
      count = 271,
      desc = locale.gettext("配方书、技能书与其他读物。"),
      id = "books",
      name = locale.gettext("书籍与资料"),
    },
    {
      count = 182,
      desc = locale.gettext("原料、燃料、制造材料与通用零件。"),
      id = "materials",
      name = locale.gettext("材料与零件"),
    },
    {
      count = 201,
      desc = locale.gettext("车辆零件、发动机、轮组与车载结构件。"),
      id = "vehicle_parts",
      name = locale.gettext("车辆部件"),
    },
    {
      count = 109,
      desc = locale.gettext("仿生安装物与高级技术物资。"),
      id = "bionics",
      name = locale.gettext("仿生与高科技"),
    },
    {
      count = 723,
      desc = locale.gettext("其余可购买、可回收但不适合归入上列分类的物品。"),
      id = "misc",
      name = locale.gettext("其他杂项"),
    },
  },
  generated_at = "2026-03-23T09:29:39.706330+00:00",
  source_root = "data/json/items",
}
